# Generated by Django 5.0 on 2024-08-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendingMachine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_photo',
            field=models.ImageField(blank=True, null=True, upload_to='product_photos/'),
        ),
    ]
